// Copyright 2025 cormoran707
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#define POINTING_DEVICE_CS_PIN GP2
#define POINTING_DEVICE_SCLK_PIN GP1
#define POINTING_DEVICE_SDIO_PIN GP0
#define POINTING_DEVICE_MOTION_PIN GP3

#define POINTING_DEVICE_MOTION_PIN_ACTIVE_LOW

#define POINTING_DEVICE_TASK_THROTTLE_MS 10

// #define POINTING_DEVICE_AUTO_MOUSE_ENABLE

// #define HOLD_ON_OTHER_KEY_PRESS